shell:
  program: /usr/bin/zsh
  args:
    - --login
env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  TERM: xterm-256color
window:
  decorations: none
  opacity: 0.9
  padding:
    x: 50
    y: 40
key_bindings:
  - { key: L, mods: Control, chars: "/usr/bin/clear && ls \x0D" }
  - { key: H, mods: Control|Shift, chars: "history | cat -l bash \x0D" }
